
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import Helper.*;
import Model.ChiefPhysician;
import Model.Doctor;
import Model.Patient;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kilic
 */
public final class LoginGUI extends javax.swing.JFrame {
   // private DBConnection conn = new DBConnection();
    DBConnection conn = new DBConnection();             //  connect sıkıntılı bakk bunaa
//

    /**
     * Creates new form Login
     */
    public LoginGUI() {
        initComponents();
    }

    /*   public void scaleImage(){  // vazgeçtim yetişmedi
JLabel lbl_logo=new JLabel(new ImageIcon(getClass().getResource("hospital.png")));
//ImageIcon icon = new ImageIcon("hospital.png");
//lbl_logo.setIcon(icon);
w_pane.add(lbl_logo);
}
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * ewrwerwerwerwerew WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        w_tabpane = new javax.swing.JTabbedPane();
        w_patientLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fld_patientTC = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_patientLogin = new javax.swing.JButton();
        fld_patientPass = new javax.swing.JPasswordField();
        w_doctorLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fld_doctorTC = new javax.swing.JTextField();
        doctorLogin = new javax.swing.JButton();
        fld_doctorPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management Information System");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("w_pane"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        w_tabpane.setBackground(new java.awt.Color(255, 255, 255));
        w_tabpane.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 15)); // NOI18N

        w_patientLogin.setBackground(new java.awt.Color(255, 255, 255));
        w_patientLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel2.setText("TC :");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 20));
        w_patientLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel3.setText("Password :");
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 20));
        w_patientLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 30));

        fld_patientTC.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        fld_patientTC.setPreferredSize(new java.awt.Dimension(70, 20));
        fld_patientTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_patientTCActionPerformed(evt);
            }
        });
        w_patientLogin.add(fld_patientTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 230, 30));

        btn_register.setText("REGISTER");
        btn_register.setPreferredSize(new java.awt.Dimension(90, 25));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        w_patientLogin.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, 30));

        btn_patientLogin.setText("LOGIN");
        btn_patientLogin.setPreferredSize(new java.awt.Dimension(90, 25));
        btn_patientLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patientLoginActionPerformed(evt);
            }
        });
        w_patientLogin.add(btn_patientLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 90, 30));

        fld_patientPass.setText("jPasswordField1");
        fld_patientPass.setPreferredSize(new java.awt.Dimension(70, 20));
        fld_patientPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_patientPassActionPerformed(evt);
            }
        });
        w_patientLogin.add(fld_patientPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 230, 30));

        w_tabpane.addTab("Patient Entry", w_patientLogin);

        w_doctorLogin.setBackground(new java.awt.Color(255, 255, 255));
        w_doctorLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel4.setText("TC:");
        jLabel4.setPreferredSize(new java.awt.Dimension(70, 20));
        w_doctorLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel5.setText("Password:");
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 20));
        w_doctorLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, -1));

        fld_doctorTC.setText("jTextField1");
        fld_doctorTC.setMinimumSize(new java.awt.Dimension(6, 31));
        fld_doctorTC.setPreferredSize(new java.awt.Dimension(70, 20));
        w_doctorLogin.add(fld_doctorTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 190, 30));

        doctorLogin.setText("LOGIN");
        doctorLogin.setPreferredSize(new java.awt.Dimension(90, 25));
        doctorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorLoginActionPerformed(evt);
            }
        });
        w_doctorLogin.add(doctorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, 30));

        fld_doctorPassword.setText("jPasswordField1");
        fld_doctorPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_doctorPasswordActionPerformed(evt);
            }
        });
        w_doctorLogin.add(fld_doctorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, 30));

        w_tabpane.addTab("Doctor Entry", w_doctorLogin);

        getContentPane().add(w_tabpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 480, 320));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 17)); // NOI18N
        jLabel1.setText("Welcome to the Hospital Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_patientTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_patientTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_patientTCActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:  done
        RegisterGUI rGUI = new RegisterGUI();
        rGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_registerActionPerformed

    private void doctorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorLoginActionPerformed
        // TODO add your handling code here: done
        if (fld_doctorTC.getText().length() == 0 || fld_doctorPassword.getText().length() == 0) {
//JoptionPane.showMessageDialog(null, "Please fill in all fields ");
            Helper.showMsg("fill"); // fill-up
        } else {

            try {
                Connection con = conn.connDb();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM user");
                while (rs.next()) {
                    if (fld_doctorTC.getText().equals(rs.getString("TC_id")) && fld_doctorPassword.getText().equalsIgnoreCase(rs.getString("User_password"))) {
//fld_doctorPassword.getText().equals(rs.getString("User_password"))
//                        
                        if (rs.getString("type").equals("ChiefPhy")) {
                            ChiefPhysician ChiefPhy = new ChiefPhysician();
                            ChiefPhy.setUser_id(rs.getInt("User_id"));
                            ChiefPhy.setUser_password("User_password");
                            ChiefPhy.setTC_id(rs.getString("TC_id"));
                            ChiefPhy.setUser_name(rs.getString("User_name"));
                            ChiefPhy.setUser_type(rs.getString("User_type"));
//System.out.println(ChiefPhy.getUser_name());
                            ChiefPhysicianGUI cGUI = new ChiefPhysicianGUI(ChiefPhy);
                            cGUI.setVisible(true);
                            dispose();
                        }
                        if (rs.getString("type").equals("doctor")) {
                            Doctor doctor = new Doctor();
                            doctor.setUser_id(rs.getInt("User_id"));
                            doctor.setUser_password("User_password");
                            doctor.setTC_id(rs.getString("TC_id"));
                            doctor.setUser_name(rs.getString("User_name"));
                            doctor.setUser_type(rs.getString("User_type"));
                            DoctorGUI dGUI = new DoctorGUI(doctor);
                            dGUI.setVisible(true);
                            dispose();
                        }

                    }

                }

            } catch (SQLException e1) {
                e1.printStackTrace();
            }

        }

    }//GEN-LAST:event_doctorLoginActionPerformed

    private void fld_doctorPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_doctorPasswordActionPerformed
        /*

fld_doktorPass = new JPasswordField();
		fld_doktorPass.setBounds(239, 57, 195, 20);
		w_doctorLogin.add(fld_doctorpassword);
         */
//TODO add your handling code here:
    }//GEN-LAST:event_fld_doctorPasswordActionPerformed

    private void fld_patientPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_patientPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_patientPassActionPerformed

    private void btn_patientLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patientLoginActionPerformed
        // TODO add your handling code here: done 
        if (fld_patientTC.getText().length() == 0 || fld_patientPass.getText().length() == 0) {
            Helper.showMsg("fill");
        } else {
            boolean key = true;
            try {
                Connection con = conn.connDb();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM user");

                while (rs.next()) {
                    if (fld_patientTC.getText().equals(rs.getString("TC_id")) && fld_patientPass.getText().equals(rs.getString("User_password"))) {
                        if (rs.getString("type").equals("patient")) {
                            Patient patient = new Patient();
                            patient.setUser_id(rs.getInt("User_id"));
                            patient.setUser_password("User_password");
                            patient.setTC_id(rs.getString("TC_id"));
                            patient.setUser_name(rs.getString("User_name"));
                            patient.setUser_type(rs.getString("User_type"));
//System.out.println(ChiefPhy.getUser_name());
                            PatientGUI pGUI = new PatientGUI(patient);
                            pGUI.setVisible(true);
                            dispose();
                            key = false;
                        }

                    }

                }

            } catch (SQLException e1) {
                e1.printStackTrace();
            }
            if (key) {
                Helper.showMsg("No such patient found, please register.");
            }
        }


    }//GEN-LAST:event_btn_patientLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_patientLogin;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton doctorLogin;
    private javax.swing.JPasswordField fld_doctorPassword;
    private javax.swing.JTextField fld_doctorTC;
    private javax.swing.JPasswordField fld_patientPass;
    private javax.swing.JTextField fld_patientTC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel w_doctorLogin;
    private javax.swing.JPanel w_patientLogin;
    private javax.swing.JTabbedPane w_tabpane;
    // End of variables declaration//GEN-END:variables

}
