
import Helper.Helper;
import Model.Patient;

import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kilic
 */
public class RegisterGUI extends javax.swing.JFrame {

    private JPanel w_pane;
    private Patient patient = new Patient();

    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {

        //w_pane = new JPanel();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fld_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fld_tcno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fld_pass = new javax.swing.JPasswordField();
        btn_register = new javax.swing.JButton();
        btn_backto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management Information System");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(350, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name Surname");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        fld_name.setText("jTextField1");
        getContentPane().add(fld_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 40));

        jLabel2.setText("T.C. Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 30));

        fld_tcno.setText("jTextField1");
        getContentPane().add(fld_tcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 40));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        fld_pass.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        fld_pass.setText("jPasswordField1");
        getContentPane().add(fld_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 40));

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 50));

        btn_backto.setText("Turn Back");
        btn_backto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backtoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_backto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        if (fld_tcno.getText().length() == 0 || fld_pass.getText().length() == 0 || fld_name.getText().length() == 0) {
            Helper.showMsg("fill");
        } else {
            try {
                boolean control = patient.register(fld_tcno.getText(), fld_pass.getText(), fld_name.getText());
                if (control) {
                    Helper.showMsg("success");
                    LoginGUI login = new LoginGUI();
                    login.setVisible(true);
                    dispose();
                } else {
                    Helper.showMsg("error");
                }
            } catch (Exception e1) {
                e1.printStackTrace();
            }
        }

    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_backtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backtoActionPerformed
        // TODO add your handling code here:

        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backto;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField fld_name;
    private javax.swing.JPasswordField fld_pass;
    private javax.swing.JTextField fld_tcno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
