
import Helper.Helper;
import Model.Clinic;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kilic
 */
public class UpdateClinicGUI extends javax.swing.JFrame {

    private static Clinic clinic;

    /**
     * Creates new form UpdateClinicGUI
     */
    public UpdateClinicGUI(Clinic clinic) {
        fld_clinicName.setText(clinic.getName());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fld_clinicName = new javax.swing.JTextField();
        btn_updateClinic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(225, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Clinic Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 40));

        fld_clinicName.setText("jTextField1");
        getContentPane().add(fld_clinicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 40));

        btn_updateClinic.setText("EDIT");
        btn_updateClinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateClinicActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updateClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateClinicActionPerformed
        // TODO add your handling code here:
        if (Helper.confirm("sure")) {
            try {
                clinic.updateClinic(clinic.getId(), fld_clinicName.getText());
                Helper.showMsg("success");
                dispose();
            } catch (SQLException e1) {
            }

        }
    }//GEN-LAST:event_btn_updateClinicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateClinicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateClinicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateClinicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateClinicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateClinicGUI frame = new UpdateClinicGUI(clinic);
                new UpdateClinicGUI(clinic).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_updateClinic;
    private javax.swing.JTextField fld_clinicName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
